schema
  @link(
    url: "https://specs.apollo.dev/federation/v2.8",
    import: ["@key", "@shareable", "@external"]
  ) {
  query: Query
  mutation: Mutation
}

extend type Query {
  pendingHosts: [User!]! @shareable
}

extend type Mutation {
  approveHost(userId: ID!): ApproveHostResponse! @shareable
  becomeHost(input: BecomeHostInput!): BecomeHostResponse! @shareable
}

interface User @key(fields: "id") {
  id: ID!
  email: String
  fullName: String
  picture: String
  role: Role
}


enum Role {
  ADMIN
  HOST
  PENDING_HOST
  GUEST
  USER
}

interface Response {
  code: Int!
  success: Boolean!
  message: String!
}

type BecomeHostResponse implements Response {
  code: Int! @shareable
  success: Boolean! @shareable
  message: String! @shareable
  user: User @shareable
}

type ApproveHostResponse implements Response {
  code: Int! @shareable
  success: Boolean! @shareable
  message: String! @shareable
  user: User @shareable
}

type Host implements User @key(fields: "id") {
  id: ID! @shareable
  email: String! @shareable
  fullName: String @shareable
  picture: String! @shareable
  role: Role! @shareable
}

type Guest implements User @key(fields: "id") {
  id: ID! @shareable
  email: String! @shareable
  fullName: String @shareable
  picture: String! @shareable
  role: Role! @shareable
}

