supergraph:
  listen: 0.0.0.0:4000 # The supergraph gateway runs on port 4000
  include_subgraph_errors:
    all: true # Propagate errors from all subgraphs

headers:
  all:
    request:
      - propagate:
          named: Authorization

cors:
  allow_any_origin: false
  origins:
    - http://localhost:3000 # Allows any locally-running client
    - https://studio.apollographql.com # Allows Apollo Studio to send queries

subgraphs:
  users:
    routing_url: http://localhost:4010/graphql # Ensure this points to your subgraph-users
    schema:
      file: ./subgraphs/users/schema.graphql  
