schema
  @link(url: "https://specs.apollo.dev/federation/v2.8", import: ["@key", "@shareable"]) {
  query: Query
  mutation: Mutation
}

scalar DateTime

type Amenity @key(fields: "id") {
  id: ID! @shareable
  name: String! @shareable
  locationId: ID! @shareable
  categoryId: ID !@shareable
  description: String! @shareable
}

interface Response {
  code: Int!
  success: Boolean!
  message: String!
}

type AddAmenityResponse implements Response {
  code: Int! @shareable
  success: Boolean! @shareable
  message: String! @shareable
  amenity: Amenity! @shareable
}

type AmenityResponse implements Response {
  code: Int! @shareable
  success: Boolean! @shareable
  message: String! @shareable
  amenity: Amenity! @shareable
}

input AmenityInput {
  name: String!
  locationId: ID!
  categoryId: ID!
  description: String
}

type Query {
  amenities: [Amenity!]! @shareable
  amenity(id: ID!): Amenity @shareable
  listingAmenities(listingId: ID!): [Amenity!]! @shareable
}

type Mutation {
  addAmenity(input: AmenityInput!): AddAmenityResponse! @shareable
  updateAmenity(id: ID!, input: AmenityInput!): AmenityResponse! @shareable
  deleteAmenity(id: ID!): AmenityResponse! @shareable
}
