schema
  @link(url: "https://specs.apollo.dev/federation/v2.8", import: ["@key", "@shareable"]) {
  query: Query
  mutation: Mutation
}

scalar DateTime

type Amenity @key(fields: "id") {
  id: ID! @shareable
  title: String! @shareable
  locationId: ID! @shareable
  category: String! @shareable
  description: String @shareable
  createdAt: DateTime! @shareable
  updatedAt: DateTime! @shareable
}

type Query {
 amenities(locationId: ID!): [Amenity!]! @shareable
}

type Mutation {
  addAmenity(name: String!): Amenity! @shareable
}
