

schema
  @link(url: "https://specs.apollo.dev/federation/v2.8", import: ["@key", "@shareable","@external"]) {
  query: Query
  mutation: Mutation
}
scalar JSON

enum CacheControlScope {
  PUBLIC
  PRIVATE
}
# Enums
enum Role {
  ADMIN
  HOST
  GUEST
  USER
  PENDING_HOST
}
type AuthPayload {
  user: User!
  accessToken: String!
}

type Mutation {
  debugCreateUser(email: String!): User
  oauthLogin(input: OAuthLoginInput!): AuthPayload
  refreshToken: AuthPayload
}
 
 input OAuthLoginInput {
  provider: String!
  payload: JSON!
}

# schema.graphql (auth subgraph)



type Query {
  getUser(id: ID!): User @shareable
  me: User @shareable 
  user(id: ID!): User @shareable
  users: [User]!@shareable
}

type User {
  id: ID!
  email: String!
  role: Role!
}