type Mutation {
  createListing(input: ListingInput!): Listing!
  updateListing(id: ID!, input: ListingInput!): Listing!
  deleteListing(id: ID!): Boolean!
}

input ListingInput {
  title: String!
  description: String!
  price: Float!
  hostId: ID!
  location: LocationInput!
  latitude: Float!
  longitude: Float!
  numOfBeds: Int!
  costPerNight: Float!
  locationType: String!
  amenityIds: [ID!]!
  listingStatus: String!
  checkInDate: String!
  checkOutDate: String!
  isFeatured: Boolean!
}

input LocationInput {
  id: ID
  name: String!
  address: String!
  city: String!
  state: String!
  zip: String!
  country: String!
  latitude: Float!
  longitude: Float!
  radius: Float!
  units: String!
}

input PictureInput {
  id: ID
  url: String!
}

input AmenityInput {
  id: ID
  category: String!
  name: String!
  description: String!
}

input ListingFilterInput {
  minPrice: Float
  maxPrice: Float
  locationType: String
  isFeatured: Boolean
}

