CREATE TABLE IF NOT EXISTS listings (
  id VARCHAR(50) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description VARCHAR(500),
  price DECIMAL(10,2),
  locationId VARCHAR(50),
  FOREIGN KEY (locationId) REFERENCES locations(id) ON DELETE SET NULL
) ENGINE=InnoDB;
