extend schema
  @link(
    url: "https://specs.apollo.dev/federation/v2.8",
    import: ["@key", "@shareable", "@external"]
  )

# Enums
enum Role {
  ADMIN
  HOST
  GUEST
}

enum OAuthProvider {
  GOOGLE
  FACEBOOK
  APPLE
  # Future: Add more here easily
}

# Scalars
scalar DateTime
scalar _Any

# Interfaces
interface Response {
  "Represents the status of the response"
  code: Int!
  "Indicates whether the operation was successful"
  success: Boolean!
  "Human-readable message for UI"
  message: String!
}

interface User @key(fields: "id") {
  id: ID!
  email: String! 
  fullName: String
  firstName: String!
  lastName: String!
  role: Role!
  picture: String!
  nickname: String!
  provider: OAuthProvider
  oauthId: String!
}

type Guest implements User @key(fields: "id") {
  id: ID!
  email: String! @shareable
  fullName: String
  firstName: String!
  lastName: String!
  picture: String! @shareable
  nickname: String! @shareable
  role: Role! @shareable
  provider: OAuthProvider @shareable
  oauthId: String! @shareable
  idToken: String! @shareable
  accessToken: String! 
  refreshToken: String 
}

type Host implements User @key(fields: "id") {
  id: ID!
  email: String! @shareable
  fullName: String
  firstName: String!
  lastName: String!
  picture: String! @shareable
  nickname: String! @shareable
  role: Role! @shareable
  provider: OAuthProvider @shareable
  oauthId: String! @shareable
  idToken: String! @shareable
  accessToken: String! 
  refreshToken: String 
  description: String @shareable
  inviteCode: String! @shareable
}


# Input Types
input SignInInput {
  email: String
  password: String
  provider: OAuthProvider
  token: String
  refreshToken: String
  oauthId: String
  idToken: String
  accessToken: String
}

input SignUpInput {
  email: String!
  password: String!
  name: String!
  nickname: String!
  role: Role = GUEST
  picture: String!
  inviteCode: String
}

input UpdatePasswordInput {
  userId: ID!
  newPassword: String!
  password: String!
}

# Auth Response Types
type AuthPayload {
  token: String! @shareable
  userId: ID! @shareable
  role: Role! @shareable
}

type SignInResponse implements Response {
 code: Int! @shareable
  success: Boolean! @shareable
  message: String! @shareable
  auth: AuthPayload @shareable
  refreshToken: String @shareable
  role: Role! @shareable
  userId: ID @shareable
}

# Password and Invite Management
type ReqResetPwdResponse implements Response {
  code: Int! @shareable
  success: Boolean! @shareable
  message: String! @shareable
  link: String! @shareable
}

type ForgotPasswordResponse implements Response {
  code: Int! @shareable
  success: Boolean! @shareable
  message: String! @shareable
  email: String! @shareable
}

type InviteCodeResponse implements Response {
  code: Int! @shareable
  success: Boolean! @shareable
  message: String! @shareable
}

# Queries and Mutations
type Mutation {
  signUp(input: SignUpInput!): AuthPayload!
  signIn(input: SignInInput!): SignInResponse!
  updatePassword(newPassword: String!, password: String!, userId: ID!): AuthPayload!
  requestResetPassword(email: String!): ReqResetPwdResponse!
  forgotPassword(email: String!): ForgotPasswordResponse!
  sendInviteCode(email: String!): InviteCodeResponse!
  logout(provider: OAuthProvider): Boolean!
}

type Query {
  getUser(id: ID!): User @shareable
  myProtectedData: ProtectedData!
}

type ProtectedData {
  message: String!
  userId: ID!
}

# Federation
type _Service {
  sdl: String
}

union _Entity = Host | Guest
