extend schema
  @link(
    url: "https://specs.apollo.dev/federation/v2.8",
    import: ["@key", "@shareable", "@external"]
  )

# Enums
enum Role {
  ADMIN
  HOST
  GUEST
}

# Scalars
scalar DateTime

interface Response {
  "Represents the status of the response"
  code: Int!
  "Indicates whether the operation was successful"
  success: Boolean!
  "Human-readable message for UI"
  message: String!
}

interface User @key(fields: "id") {
  id: ID!
  email: String! 
  fullName: String
  name:String
  firstName: String!
  lastName: String!
  role: Role!
  picture: String!
  nickname: String!
  provider: OAuthProvider
  oauthId: String!
}

type Guest implements User @key(fields: "id") {
  id: ID!
  email: String! @shareable
  name: String @shareable
  fullName: String @shareable
  firstName: String! @shareable
  lastName: String! @shareable
  picture: String! @shareable
  nickname: String! @shareable
  role: Role! @shareable
  provider: OAuthProvider @shareable
  oauthId: String! @shareable
  idToken: String! @shareable
  accessToken: String! @shareable
  refreshToken: String @shareable
}

type Host implements User @key(fields: "id") {
  id: ID!
  email: String! @shareable
  name: String @shareable
  fullName: String @shareable
  firstName: String! @shareable
  lastName: String! @shareable
  picture: String! @shareable
  nickname: String! @shareable
  role: Role! @shareable
  provider: OAuthProvider @shareable
  oauthId: String! @shareable
  idToken: String! @shareable
  accessToken: String! @shareable
  refreshToken: String @shareable
  description: String @shareable
  inviteCode: String! @shareable
}

# Input Types
input SignInInput {
  email: String
  password: String
  provider: OAuthProvider
  token: String
  refreshToken: String
  oauthId: String
  idToken: String
  accessToken: String
}

input SignUpInput {
  email: String!
  password: String!
  name: String!
  nickname: String!
  role: Role = GUEST
  picture: String!
  inviteCode: String
}

input UpdatePasswordInput {
  userId: ID!
  newPassword: String!
  password: String!
}

# Response Types
type AuthPayload {
  token: String @shareable
  userId: ID @shareable
  role: Role @shareable
  accessToken: String @shareable
  refreshToken: String @shareable
}

type SignInResponse implements Response {
  code: Int! @shareable
  success: Boolean! @shareable
  message: String! @shareable
  auth: AuthPayload @shareable
  refreshToken: String @shareable
  role: Role! @shareable
  userId: ID !@shareable
  user:User @shareable
  token: AuthPayload @shareable
}

type SignUpResponse implements Response {
  code: Int! @shareable
  success: Boolean! @shareable
  message: String! @shareable
  auth: AuthPayload @shareable
  refreshToken: String @shareable
  role: Role! @shareable
  userId: ID !@shareable
  picture: String @shareable
  name: String @shareable
}

type ReqResetPwdResponse implements Response {
  code: Int! @shareable
  success: Boolean! @shareable
  message: String! @shareable
  link: String! @shareable
}

type ForgotPasswordResponse implements Response {
  code: Int! @shareable
  success: Boolean! @shareable
  message: String! @shareable
  email: String! @shareable
}

type InviteCodeResponse implements Response {
  code: Int! @shareable
  success: Boolean! @shareable
  message: String! @shareable
}

# Queries and Mutations
type Mutation {
  signUp(input: SignUpInput!): SignUpResponse! @shareable 
  signIn(input: SignInInput!): SignInResponse! @shareable 
  oauthSaveUser(input: OAuthInput!): AuthPayload! @shareable
  updatePassword(input: UpdatePasswordInput!): AuthPayload! @shareable
  requestResetPassword(email: String!): ReqResetPwdResponse! @shareable
  forgotPassword(email: String!): ForgotPasswordResponse! @shareable
  sendInviteCode(email: String!): InviteCodeResponse! @shareable
  logout(provider: OAuthProvider): Boolean! @shareable
  createUser(name: String!, email: String!): User @shareable
  updateUser(id: ID!, name: String): User @shareable
  verifyGoogleToken(token: String): AuthPayload @shareable
  verifyFacebookToken(token: String): AuthPayload @shareable
  verifyAppleToken(token: String): AuthPayload @shareable
  verifyTwitterToken(token: String): AuthPayload @shareable
}

enum OAuthProvider {
  GOOGLE
  FACEBOOK
  APPLE
  GITHUB
}


input OAuthInput {
  provider: OAuthProvider!
  token: String!
  refreshToken: String
  email: String
  name: String
}
type Query {
  getUser(id: ID!): User @shareable
  user(id: ID!): User @shareable
  users: [User]! @shareable
}

# Federation
type _Service {
  sdl: String
}

union _Entity = Host | Guest